In [29]:
#Utilizando a Biblioteca Numpy para a relização de cálculos: Álgebra Linear: Vetores(unidimensional - lista) 
#e Matrizes(bidimensional-duas ou mais dimensões).
#Uma imagem é uma matriz :-)
#Matriz: Linha x coluna
#A diagonal é a ordem da matriz

In [30]:
#Importando a Biblioteca

import numpy as np


In [31]:
#Operações com arrays
#Estruturas unidimensionais - Criando um array (listas) - A
a1 = np.array(['Spark','Hadoop','Python','R'])

In [32]:
a1

array(['Spark', 'Hadoop', 'Python', 'R'], dtype='<U6')

In [33]:
#Estruturas Bidimensionais (Matrizes)
a2 = np.array([['Altura','Largura','Profundidade'],[42, 78, 10]]) 

In [34]:
a2

array([['Altura', 'Largura', 'Profundidade'],
       ['42', '78', '10']], dtype='<U12')

In [35]:
#Exemplo:
a3 = np.array([[10,20,30],[40,50,60]])

In [36]:
a3

array([[10, 20, 30],
       [40, 50, 60]])

In [37]:
#Tamanho do array (shape) - tamamnho da matriz
print(a1.shape)
print(a2.shape)

(4,)
(2, 3)


In [38]:
#Dimensoes do Array
a1.ndim

1

In [39]:
# Quando utilizar os parenteses?
# O uso de parênteses reflete uma AÇÃO, enquanto a ausência, reflete uma característica

In [40]:
#O método max() não funciona em arrays de tipo heterogeneo
a3.max()

60

In [41]:
# Atributo
a2.ndim

2

In [42]:
#Método Arange
array = np.arange(20)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [43]:
# Usando start/end - de 0 a 100 de 10 em 10
array = np.arange(0, 100, 10)

In [44]:
array

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [45]:
# IMPORTANTE: A diferença do linspace para o arange é que:  no arange o ultimo argumento é o incremento,
# e no linspace o último argumento é o número de elementos do vetor (aleatorio)
matriz = np.linspace(0, 10, 20)
matriz

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [46]:
matriz = np.linspace(0,10,5)
matriz

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [47]:
matriz = np.linspace(0,5,5)
matriz

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [48]:
#ESTRUTURAS DE MATRIZES:

In [49]:
#numpy.zeros

matriz = np.zeros((10, 10))
matriz

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [50]:
#numpy.ones
matriz = np.ones((2, 3))
matriz

array([[1., 1., 1.],
       [1., 1., 1.]])

In [51]:
# Numpy.eye - Produz uma matriz do tipo Identitiy
matriz = np.eye(10)
matriz

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [52]:
# numpy.diag produz o mesmo resultado, porem podemos definir os numeros das diagonais

matriz = np.diag((2,4,6,8,10,12,14,16,18,20))
matriz

array([[ 2,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  4,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  6,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  8,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 10,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, 12,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 14,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 16,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0, 18,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0, 20]])

In [53]:
# numpy.empty produz uma matriz vazia

matriz = np.empty((10,5))
matriz

array([[ 1.11893226e-311,  1.11896010e-311,  5.03835034e+223,
         7.28929489e-086,  6.01346953e-154],
       [ 7.25906902e-043,  1.14303483e+243,  6.43711403e+170,
         3.67292746e+194,  2.64521820e+185],
       [ 9.77443709e+199,  3.65582216e+233,  1.05034473e-153,
         6.01346953e-154,  8.26219277e-072],
       [ 1.35350041e+166,  3.05467722e+223,  7.49762279e+247,
         9.82986171e+242,  8.09375162e+054],
       [ 3.64913061e+233,  4.47593784e-091,  1.04419813e+228,
         2.21208742e+214,  1.27664645e-152],
       [ 8.79345187e+199,  9.19596581e+170,  2.66064808e-260,
        -3.63002359e+125,  3.32653114e-111],
       [ 7.50057371e+247,  7.93541578e+069,  3.86093052e+228,
         6.20524036e+228, -5.52367813e+127],
       [ 4.98112458e+127,  3.11732882e+150,  5.30486669e+180,
         2.41577945e-311,  7.69152976e+218],
       [ 7.49994980e+247,  1.79209390e-313,  7.52516610e+058,
         5.26616474e-090,  7.48269334e+247],
       [ 1.20990565e+185,  7.27455743

In [54]:
#NUmpy tile
np.tile(np.array([[1, 2], [3, 4], [5, 6]]), 3)

array([[1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4],
       [5, 6, 5, 6, 5, 6]])

In [55]:
#Num de vezes do array na vertical , num de vezes array na horizontal
np.tile(np.array([[1, 2], [3, 4], [5, 6]]), (3,6)) 

array([[1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4, 3, 4, 3, 4, 3, 4],
       [5, 6, 5, 6, 5, 6, 5, 6, 5, 6, 5, 6],
       [1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4, 3, 4, 3, 4, 3, 4],
       [5, 6, 5, 6, 5, 6, 5, 6, 5, 6, 5, 6],
       [1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4, 3, 4, 3, 4, 3, 4],
       [5, 6, 5, 6, 5, 6, 5, 6, 5, 6, 5, 6]])

In [56]:
##Tipos de dados

In [ ]:
import numpy as np

In [27]:
#Criando o array float (com pontos flutuantes)
a = np.array([-10, 10, 20, 30], dtype = 'float')

In [28]:
a

array([-10.,  10.,  20.,  30.])

In [57]:
#A propriedade dtype me retorna o tipo dos elementos do array

a.dtype

dtype('float64')

In [58]:
#Inteiro
b = np.array([-10, 10, 20, 30])
b.dtype

dtype('int32')

In [59]:
#float
c = np.array([10,20,30,40.5])
c.dtype

dtype('float64')

In [ ]:
#string

d = np.array(['Universidade','dos','Dados'])

In [60]:
#Tipo boleano (sem aspas)
e = np.array([False, False, True])

In [61]:
e.dtype

dtype('bool')

In [62]:
#Cast de arrays
f = np.array([-9, 10, 20.7])
f.dtype

dtype('float64')

In [63]:
#Cast com a função astype
f.astype(int)

array([-9, 10, 20])

# Operações aritméticas

In [64]:
# a função arange cria um array

array = np.arange(0,5)
array

array([0, 1, 2, 3, 4])

In [65]:
array = np.arange(0, 10) * 10

In [66]:
array

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [67]:
# Potencia
array = np.arange(10) ** 2

In [68]:
array

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [ ]:
# Operações aritméticas entre arrays

In [ ]:
#Exemplo:
#A (0-1-2-3-4-5-6-7-8-9)
#B (1-2-3-4-5-6-7-8-9-10)

In [69]:
arrayA = np.arange(0,10)
arrayB = np.arange(0,10)+1

In [70]:
arrayA

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
arrayB

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [72]:
# Soma
arrayA + arrayB

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [73]:
# Subtração
arrayA - arrayB

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1])

In [74]:
# Divisão
arrayA / arrayB

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ,
       0.83333333, 0.85714286, 0.875     , 0.88888889, 0.9       ])

In [75]:
# Multiplicação
arrayA * arrayB

array([ 0,  2,  6, 12, 20, 30, 42, 56, 72, 90])

In [76]:
# Comparacao de arrays
arrayA == arrayB

array([False, False, False, False, False, False, False, False, False,
       False])

In [77]:
arrayA > arrayB

array([False, False, False, False, False, False, False, False, False,
       False])

In [78]:
arrayA < arrayB

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [ ]:
#Tabela verdade para comparar dois arrays: operador lógico AND

In [79]:
array1 = np.array([True,False,True,False])
array2 = np.array([False,False,True, False])
np.logical_and(array1, array2)

array([False, False,  True, False])

In [ ]:
#Tabela verdade para comparar dois arrays: operador lógico OR

In [80]:
array1 = np.array([True,False,True,False])
array2 = np.array([False,False,True, False])
np.logical_or(array1, array2)

array([ True, False,  True, False])

In [ ]:
#Arrays com tamanhos diferentes: não podemos somar e multiplicar de forma simples
Exemplo: A + B ou A * B
A = np.array([1,2,3,4,5])
B = np.array([1,2,3])

In [81]:
A = np.array([2,4,6])
B = np.array([2,2,2])

In [82]:
#Hadmard Product

A * B

array([ 4,  8, 12])

In [83]:
#Dot Product

print(np.dot(A,B))

24


In [84]:
A = np.array([3,7,10])
B = np.array([9,3,2])

In [85]:
#Hadmard Product (multiplicação)

A * B

array([27, 21, 20])

In [86]:
#Soma dos resultados
print(np.dot(A,B))

68


In [ ]:
#Cópias de arrays

In [87]:
A = np.arange(10)

In [88]:
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [89]:
B = A[5:]
A[:] = 0

In [90]:
B

array([0, 0, 0, 0, 0])

In [91]:
A

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [92]:
A = np.arange(10)

In [93]:
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [94]:
B = A[5:].copy()

In [95]:
B

array([5, 6, 7, 8, 9])

In [96]:
A[:] = 0

In [97]:
A

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [98]:
B

array([5, 6, 7, 8, 9])